apiVersion: 1

datasources:
  - name: Portfolio Postgres
    uid: postgres-main
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: false
    editable: true
